# syntax = devthefuture/dockerfile-x

ARG MACHINE
ARG ARCH
ARG ALPINE_VERSION
ARG HOSTNAME
ARG KERNEL_IMAGE
ARG VIRT_BACKEND
ARG SERIAL_PORT
ARG SERIAL_BAUD
ARG UPD8_KEYS_FILE
ARG UPD8_MACHINE_REG_TKN_FILE
ARG SSL_CERT
ARG SSH_PUBLIC_KEY
ARG DISTRO_VERSION_MAJOR
ARG DISTRO_VERSION_MINOR
ARG DISTRO_VERSION_PATCH

INCLUDE alpine/Dockerfile
INCLUDE apps/Dockerfile
INCLUDE upd8/Dockerfile
INCLUDE machine/Dockerfile
INCLUDE virt-backend/Dockerfile
INCLUDE ca-certificates/Dockerfile
INCLUDE openssh/Dockerfile
INCLUDE ostree-initramfs/Dockerfile
INCLUDE ostree/Dockerfile
