ARG SSH_PUBLIC_KEY

# install openssh
RUN apk add --no-cache openssh

RUN if [ -n "${SSH_PUBLIC_KEY}" ]; then \
      # install custom public key
      mkdir -p ${HOME}/.ssh; \
      echo "${SSH_PUBLIC_KEY}" > ${HOME}/.ssh/authorized_keys; \
      chmod 600 ${HOME}/.ssh/authorized_keys; \

      # disable password authentication
      sed -i "s/^#PasswordAuthentication yes/PasswordAuthentication no/" \
        /etc/ssh/sshd_config; \
    fi
